import { chromium } from "playwright";
import http from "node:http"; import fs from "node:fs"; import path from "node:path";
import { createSbStub } from "./test/fixtures/sb-api.mjs";
const root = process.cwd(), out = process.argv[2];
const types = { ".html":"text/html", ".css":"text/css", ".js":"text/javascript", ".mjs":"text/javascript", ".svg":"image/svg+xml", ".png":"image/png", ".webmanifest":"application/manifest+json" };
const srv = http.createServer((q, r) => { let p = decodeURIComponent(q.url.split("?")[0]); if (p.endsWith("/")) p += "index.html";
  try { const b = fs.readFileSync(path.join(root, p)); r.writeHead(200, {"content-type": types[path.extname(p)] || "application/octet-stream"}).end(b); } catch { r.writeHead(404).end(); } });
await new Promise(ok => srv.listen(0, ok));
const base = `http://127.0.0.1:${srv.address().port}/`;
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const stub = createSbStub({ demo: true, premium: process.argv[3] === "premium" });
await ctx.route("**/api.thewizardofoza.com/**", async (route) => { const req = route.request(); let body=null; try{body=req.postDataJSON()}catch{}
  const { status, json } = stub.handler(req.url(), req.method(), body, req.headers());
  route.fulfill({ status, contentType: "application/json", body: JSON.stringify(json), headers: { "access-control-allow-origin": new URL(base).origin, "access-control-allow-credentials": "true" } }); });
const pg = await ctx.newPage();
pg.on("pageerror", e => console.log("pageerror", e.message));
await pg.goto(base, { waitUntil: "networkidle" });
const shot = async (n) => { await pg.waitForTimeout(400); await pg.screenshot({ path: `${out}/${n}.png` }); };
await shot("1-onboarding");
await pg.locator(".team-toggle", { hasText: "Chiefs" }).click();
await pg.locator(".team-toggle", { hasText: "Eagles" }).click();
await pg.locator("button", { hasText: "Show my favorites" }).click();
await shot("2-favorites");
await pg.locator('.tab[data-view="news"]').click(); await shot("3-news");
await pg.locator('.tab[data-view="scorecard"]').click(); await shot("4-results");
await pg.locator(".seg", { hasText: "Pick'em" }).click(); await pg.locator(".pick-btn").first().waitFor();
await pg.locator(".pick-row").first().locator(".pick-btn").first().click(); await shot("5-pickem");
await pg.locator('.tab[data-view="fantasy"]').click(); await pg.locator(".slot-row").first().waitFor();
await pg.locator(".slot-pick").first().click(); await pg.locator(".picker-row", { hasText: "Jalen" }).click();
await shot("6-fantasy");
await pg.locator('.tab[data-view="players"]').click(); await pg.locator("#view-players input[type=search]").fill("st"); await shot("7-players");
await pg.locator("#view-players .player-row").first().click(); await shot("8-player-sheet");
await pg.keyboard.press("Escape");
await pg.locator('.tab[data-view="scorecard"]').click(); await pg.locator(".seg", { hasText: "Results" }).click();
await pg.locator("#view-scorecard .event-card").first().click(); await shot("9-game-sheet");
await pg.keyboard.press("Escape");
await pg.locator("#settings-btn").click(); await shot("10-settings");
await b.close(); srv.close();
